### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by Bakhshi007** [7777nft/hashlips_art_engine#1]
> hashlips_art_engine@1.1.1 build
> node index.js

D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
PS D:\CV\generate-nfts-main\hashlips_art_engine-main> node index.js
D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at setSource (D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at D:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (D:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:184:12)
    at D:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)

**Comment by Bakhshi007** [comment]
Hi Guys ,
Any solution?
